# DataSource - H2 in-memory
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:caixaverso;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create

# ViaCEP REST Client
quarkus.rest-client.viacep-api.url=https://viacep.com.br

# Reguladora (mock server local) REST Client
quarkus.rest-client.reguladora-api.url=http://localhost:8080

# Security - Elytron Properties File
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true

quarkus.security.users.embedded.users.gerente=gerente123
quarkus.security.users.embedded.roles.gerente=Gerente,Usuario

quarkus.security.users.embedded.users.usuario=usuario123
quarkus.security.users.embedded.roles.usuario=Usuario
